import React from "react";
import axios from "axios";

function wordList() {
    return [
        "Family",
        "Freedom",
        "Security",
        "Loyalty",
        "Intelligence",
        "Hedonism",
        "Connection",
        "Creativity",
        "Humanity",
        "Success",
        "Flatulence",
        "Respect",
        "Invention",
        "Diversity",
        "Generosity",
        "Cannibalism",
        "Integrity",
        "Finesse",
        "Love",
        "Openness",
        "Communism",
        "Religion",
        "Order",
        "Advancement",
        "Playfulness",
        // "Forgiveness",
        // "Excitement",
        // "Change",
        // "Goodness",
        // "Involvement",
        // "Faith",
        // "Wisdom",
        // "Beauty",
        // "Caring",
        // "Growth",
        // "Endurance",
        // "Honesty",
        // "Adventure",
        // "Kindness",
        // "Teamwork",
        // "Career",
        // "Communication",
        // "Learning",
        // "Excellence",
        // "Innovation",
        // "Quality",
        // "Commonality",
        // "Contribution",
        // "Spirituality",
        // "Strength",
        // "Entertainment",
        // "Wealth",
    ];
}

export default wordList;
