import React from "react";
import axios from "axios";

function wordList() {
    return [
        "Family",
        "Freedom",
        "Security",
        "Loyalty",
        "Intelligence",
        "Connection",
        "Creativity",
        "Humanity",
        "Success",
        "Respect",
        "Invention",
        "Diversity",
        "Generosity",
        "Integrity",
        "Finesse",
        "Love",
        "Openness",
        "Hedonism",
        "Religion",
        "Order",
        "Advancement",
        "Playfulness",
        "Forgiveness",
        "Excitement",
        "Flatulence",
        "Change",
        "Goodness",
        "Cannibalism",
        "Involvement",
        "Faith",
        "Wisdom",
        "Beauty",
        "Caring",
        "Growth",
        "Endurance",
        "Honesty",
        "Adventure",
        "Kindness",
        "Teamwork",
        "Career",
        "Communication",
        "Learning",
        "Excellence",
        "Innovation",
        "Quality",
        "Communism",
        "Commonality",
        "Contributing",
        "Spiritualism",
        "Strength",
        "Entertainment",
        "Wealth",
    ];
}

export default wordList;
