import React from 'react';

function wordList() {
    return (
        [
            'Family',
            'Freedom',
            'Security',
            // 'Loyalty',
            // 'Intelligence',
            // 'Connection',
            // 'Creativity',
            // 'Humanity',
            // 'Success',
            // 'Respect',
            // 'Invention',
            // 'Diversity',
            // 'Generosity',
            // 'Integrity',
            // 'Finesse',
            // 'Love',
            // 'Openness',
            // 'Religion',
            // 'Order',
            // 'Advancement',
            // 'Playfulness',
            // 'Forgiveness',
            // 'Excitement',
            // 'Change',
            // 'Goodness',
            // 'Involvement',
            // 'Faith',
            // 'Wisdom',
            // 'Beauty',
            // 'Caring',
            // 'Growth',
            // 'Endurance',
            // 'Honesty',
            // 'Adventure',
            // 'Kindness',
            // 'Teamwork',
            // 'Career',
            // 'Communication',
            // 'Learning',
            // 'Excellence',
            // 'Innovation',
            // 'Quality',
            // 'Commonality',
            // 'Contributing',
            // 'Spiritualism',
            // 'Strength',
            // 'Entertainment',
            // 'Wealth',
        ]
    );
}

export default wordList;